version: '3.8'
services:
  webapp:
    image: java:latest
    #container_name: webapp
    environment:
      - DB_URL=jdbc:mysql://database:${DB_PORT}/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
#    volumes:
#     - webapp_data:/
    expose:
      - 8080
    ports:
      - "8888:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - pipeline_testing

  database:
    image: mariadb:latest
    #container_name: database
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - sql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      #test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pipeline_testing

volumes:
  sql_data:
      driver: local
#  webapp_data:
#    driver: local

networks:
  pipeline_testing:
      driver: bridge
